### PR TITLE
Fix for "corrupted zip. could not find central dir" issue.

### PR DESCRIPTION
**Pull request by johanatan**
See #lumo history on #clojurians for deeper explanation.

### CODE REVIEW

**Comment by dundalek** [comment]
Yeah I am definitely looking to upgrade to the next version of lumo, there are also other issues it fixes. I wonder whether they are planning to release a stable version soon, or at least a beta.

**Comment by johanatan** [comment]
Well I think this PR is pretty safe. The `1.9.0-alpha` tagged release seems pretty stable.

**Comment by dundalek** [comment]
Sorry for the late reply, I was out on a vacation for a week. It seems closh is broken on `1.9.0-alpha` :(
CI is reporting error `Can't recur here at line 56 closh/reader.cljs`.

**Comment by dundalek** [comment]
I found out the fix for the recur issue, so I merged and released this. Thanks

**Pull request merged**
