### PR TITLE
Experiment with nrepl

### PR DESCRIPTION
**Pull request by jeroenvandijk**
Although this is easy, not sure what the best way to add it is, as you will get port conflicts and the boot time is at least doubled. But here we go:

With dependency added, change `~/.closhrc` to:

```
(defn closh-prompt []
  "$ (custom):")

(def nrepl-port 7888)
(println "Starting nrepl at" nrepl-port)
(use '[clojure.tools.nrepl.server :only (start-server stop-server)])
(defonce server (start-server :port nrepl-port))
```
Start shell
```
➜  ~ java -jar project.jar
Starting nrepl at 7888
$ (custom):
```
In another shell
```
➜  ~ lein repl :connect 7888
Connecting to nREPL at 127.0.0.1:7888
REPL-y 0.3.7, nREPL 0.2.13
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_141-b15
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (in-ns 'cDisplay all 120 possibilities? (y or n)
user=> (in-ns 'closh.zero.
closh.zero.builtin              closh.zero.compiler             closh.zero.core                 closh.zero.env                  closh.zero.frontend.main        closh.zero.frontend.rebel
closh.zero.macros               closh.zero.parser               closh.zero.pipeline             closh.zero.platform.io          closh.zero.platform.process     closh.zero.reader
closh.zero.service.completion   closh.zero.util
user=> (in-ns 'closh.zero.
```

### CODE REVIEW

**Comment by jeroenvandijk** [comment]
For #88

**Comment by dundalek** [comment]
This is a great starting point.

I image the best way would be to start nrepl server only when needed explicitly. If we add the CLI options then one could launch something like `closh -c "(start-nrepl-server 7888)"` (or Emacs could launch it when nrepl connection is about to be made).

Second thing is how to include dependencies. When launching closh with the `clojure` cli then it is easy. When using the JAR build I imagine best would be to utilize `tools.deps` to allow loading deps on-demand. But this would need more investigation how to modify classpath during runtime or inject to the dynamic classloader.

**Comment by jeroenvandijk** [comment]
Yeah I think this is just the proof that you were right, that it can done by just including the nrepl in `~/.closhrc`. 

Things like this should be lazily initialised (including the require) I think. This prevents growing start up times while having it quickly when necessary.

Another idea is for closh to only provide something to include external libraries dynamically, by request, on the classpath. Something like `set-env!` in `boot-clj` via pomegrate [1].

Maybe there is actually some synergie between `boot-clj` and `closh` possible. One could call something that would start `boot` and give access to everything `boot-clj` offers (including isolated pods). Wild idea so far :)


[1] https://github.com/boot-clj/boot/wiki/Boot-Environment#env-keys

**Comment by dundalek** [comment]
Yeah, including [pomegranate](https://github.com/cemerick/pomegranate) makes sense. It seems that is what boot uses internally for resolution and loading.

I need to take a closer look at the boot pods. What would be an example use case for them?

Closh can be also run via tools.deps and one can customize environment with [aliases](https://clojure.org/reference/deps_and_cli#_aliases). Although that starts a bit slower than running the uberjar.

**Comment by jeroenvandijk** [comment]
Regarding the pods, maybe I'm getting ahead of myself a bit, please forgive me. Now that I have Clojure constantly at my fingertips (still getting used to the idea), I start to imagine how I could do all kinds of new things. 

E.g. I imagine how I could use something like Incanter to filter and visualize a csv file in my current directory. Not sure if that's your wildest fantasy (lol), but I hope it makes sense. I can imagine some other examples of libraries that you will want to use (more) on the command line.

This all sounds great, but introducing libraries has a cost. You will have to load these libraries, put it on the classpath before it can work. Maybe we can be smart about lazy loading so that you only pay the price for when you need something. However, the more libraries you use simultaneously  the bigger chance you have of weird conficts (the tools.reader issue is a great example). `boot` has identified this issue and has engineered a solution for it with `pods`. A pod isolaties different programs/processes and prevents these conflicts. To make it all workable and fast there is a pod pool.

Going even further, we have been talking about a script mode. Let's say GraalVM will work for a particular feature set, what if we want to go beyond this feature set, but still expect a fast boot time. Maybe here too, the work that has been put in `boot` could be used in a client/server model. The client would be a lean thing, to make quick start times work, that knows how to do all the basic bash / clojure stuff, but it would *not* have all these libraries. For libraries it would connect to this system wide process* based on boot that would have access to all these libraries and with a `pod` poll it would make this isolated and pretty fast.

Ok having said all this, it is just an idea and I'm not sure yet if it's a good one. It also a solution to a problem that doesn't yet exist.

* We can do this safely, because it's Clojure

**Comment by dundalek** [comment]
Love your thoughts. Having something like Incanter at the finger tips on the command line sounds awesome!

Thanks for the explanation of pods, that makes total sense. I wonder if it would be possible to include pods as a library. Definitely an area worth investigating.

Yeah, client/server model might be an interesting option somewhere down in the future. It might solve the startup time and help to bring memory usage down. I imagine the client would not need the dynamic eval stuff so it should be made easily graalified :) Another wild idea would be to write the client in a language like Rust or Go.

**Comment by jeroenvandijk** [comment]
Cool! Happy to hear it's not just me that would love that.

I think it's possible to include boot (parts) as a library. I might try that next week.

I was thinking about the client/server concept. I just remembered the telnet example from https://clojure.org/reference/repl_and_main I guess a good example of a very thin client. A closh client could also connect via a repl-like connection and would have to be able to do the following for it to work:

* find the backend (via config file in distribution?)
* start a backend process if there isn't one running and wait
* forward commands / scripts to backend
* Do something with autocompletions
* close connection on shell exit

The server would need to keep a session (pod?) per connection. I wonder if the new prepl addition will give us a particular benefit for a tool like this.

I don't know much about rust or go, but I'm guessing these platforms would be a good fit for the requirements of such a lean thin client. Or did you mean you want to have a real clojure interpreter in those languages?

**Comment by jcburley** [comment]
I don't understand most of what's being discussed above, but wanted to mention (as a reminder) that there's already a "Clojure-light" interpreter written in Go, and I've recently put my first script using it into production on my server:

https://github.com/candid82/joker

It's missing lots of stuff, and is itself single-threaded (though the Go runtime uses multiple threads under the hood).

**Comment by dundalek** [comment]
I was thinking to have a lean client without eval in Rust or Go. But I think I got carried away here, since it would require nRepl client implementation which would not be so easy.

@jeroenvandijk Yeah, the thin client as you describe it makes sense to me. I imagine a session could be a separate pod+thread. Additional part to ones you mentioned would be to redirect stdio, e.g. could you run something like vim over it. I think prepl should be simpler than nrepl, but I have not found any documentation or usage of it.

**Comment by dundalek** [comment]
@jeroenvandijk I included pomegranate and added an initial nREPL recipe based on the experiments above in https://github.com/dundalek/closh/commit/6b644b0e24aa9c3d29882232f3eb56d062a87939. Thanks for the research that made it possible, I am closing this now.

**Pull request closed without merging**
