### PR TITLE
logo

### PR DESCRIPTION
**Pull request by batarian71**

### CODE REVIEW

**Comment by dundalek** [comment]
Sweet, thanks. Do you have also the source format, SVG maybe?

**Comment by dundalek** [comment]
I was too quick to hit merge, we should probably add a license and credits to readme.

**Comment by batarian71** [comment]
Here is the svg file. 

https://drive.google.com/open?id=1PEDX3WzU24Q1vQoP8-YxdFE-QD716TYe

**Comment by batarian71** [comment]
You can add this license.


https://creativecommons.org/licenses/by/4.0/

**Comment by dundalek** [comment]
I updated the readme. Thanks again for the contribution.

**Pull request merged**
