### PR TITLE
Fix shell completion bugs #162

### PR DESCRIPTION
**Pull request by johannesloetzsch**

### CODE REVIEW

**Comment by dundalek** [comment]
What OS are you using?

The approach of `#!/usr/bin/env -S bash -i` will break on Linux (at least on Ubuntu), so it is not a good option.

I think the alternative solution might be to find out where the bash_completion script is located and add an extra path to try.

**Comment by johannesloetzsch** [comment]
> What OS are you using?

I use the Linux Distribution NixOS.

> The approach of `#!/usr/bin/env -S bash -i` will break on Linux (at least on Ubuntu), so it is not a good option.

The [split-string option](https://github.com/coreutils/coreutils/commit/668306ed86c8c79b0af0db8b9c882654ebb66db2) was added to coreutils in April 2018. Ubuntu should support it since 18.10

> I think the alternative solution might be to find out where the bash_completion script is located and add an extra path to try.

NixOS allows having multiple versions being installed at the same time at different path at dynamic paths below /nix/store/. So an additional hardcoded path will not help.

I see 3 different ways to solve it:
1. The shebang from this pull request requiring a not too long outdated version of coreutils.
2. Loading `_completion_loader` by `. $(which bash) -i` into a non-interactive bash.
3. A more dirty workaround would be, that I patch the shebang, while the nix-package is created.

How do you thing? Should we give 2. a try?

**Comment by johannesloetzsch** [comment]
This would evaluate the path where the bash_completion script is located at nixos

**Comment by dundalek** [comment]
cool, thank you :+1:

**Pull request merged**
